-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 17:15:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aut
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aut
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aut` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aut` ;

-- -----------------------------------------------------
-- Table `aut`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aut`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL COMMENT 'Логин пользователя',
  `password` VARCHAR(100) NOT NULL COMMENT 'Хэш пароля',
  `salt` VARCHAR(100) NOT NULL COMMENT 'Соль для пароля',
  `last_login` DATETIME NULL DEFAULT NULL COMMENT 'Дата последнего посещения',
  `email` VARCHAR(25) NULL DEFAULT NULL COMMENT 'Email пользователя',
  `phone` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Телефон пользователя',
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aut`.`visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aut`.`visits` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL COMMENT 'Логин пользователя',
  `visits_count` INT NULL DEFAULT '0' COMMENT 'Количество посещений',
  `auth_hash` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Хэш авторизации',
  `password_change_date` DATETIME NULL DEFAULT NULL COMMENT 'Дата изменения пароля',
  PRIMARY KEY (`ID`),
  INDEX `username` (`username` ASC) VISIBLE,
  CONSTRAINT `visits_ibfk_1`
    FOREIGN KEY (`username`)
    REFERENCES `aut`.`users` (`username`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `aut` ;

-- -----------------------------------------------------
-- procedure AddUser
-- -----------------------------------------------------

DELIMITER $$
USE `aut`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AddUser`(IN p_username VARCHAR(50), IN p_password VARCHAR(255), IN p_email VARCHAR(100), IN p_phone VARCHAR(20), OUT p_result VARCHAR(255))
BEGIN
    DECLARE password_hash VARCHAR(255);
    DECLARE salt VARCHAR(255);
    DECLARE is_password_valid BOOLEAN;
    
    SET is_password_valid = (p_password REGEXP '[0-9]' AND LENGTH(p_password) > 8);
    
    IF NOT is_password_valid THEN
        SET p_result = 'Введите пароль, удовлетворяющий условиям...';
    ELSE
        SET salt = SHA1(RAND());

        SET password_hash = SHA1(CONCAT(p_password, salt));
        
        INSERT INTO `users` (`username`, `password`, `salt`, `last_login`, `email`, `phone`)
        VALUES (p_username, password_hash, salt, NOW(), p_email, p_phone);
        
        SET p_result = 'Пользователь успешно зарегистрирован.';
    END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function CheckPasswordRequirements
-- -----------------------------------------------------

DELIMITER $$
USE `aut`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `CheckPasswordRequirements`(p_password VARCHAR(255)) RETURNS tinyint(1)
    DETERMINISTIC
BEGIN
    DECLARE is_valid BOOLEAN;
    SET is_valid = (p_password REGEXP '[0-9]' AND LENGTH(p_password) > 8);
    RETURN is_valid;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `aut`;

DELIMITER $$
USE `aut`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `aut`.`AddUserVisit`
AFTER INSERT ON `aut`.`users`
FOR EACH ROW
BEGIN
    INSERT INTO `visits` (`username`, `visits_count`, `auth_hash`, `password_change_date`)
    VALUES (NEW.`username`, 0, SHA1(CONCAT(RAND(), MD5(NOW()))), NOW());
END$$

USE `aut`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `aut`.`UpdateLastLoginAndVisits`
AFTER UPDATE ON `aut`.`users`
FOR EACH ROW
BEGIN
    -- Обновление даты последнего посещения
    UPDATE `users` SET `last_login` = NOW() WHERE `username` = NEW.`username`;
    
    -- Увеличение счетчика посещений и генерация хэша сессии
    UPDATE `visits` SET `visits_count` = `visits_count` + 1, `auth_hash` = SHA1(CONCAT(RAND(), MD5(NOW()))) WHERE `username` = NEW.`username`;
END$$

USE `aut`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `aut`.`UpdateVisitsCount`
AFTER UPDATE ON `aut`.`users`
FOR EACH ROW
BEGIN
    IF NEW.`last_login` IS NOT NULL THEN
        UPDATE `visits` SET `visits_count` = `visits_count` + 1 WHERE `username` = NEW.`username`;
    END IF;
END$$


DELIMITER ;
