-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 17:12:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema boots
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boots
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boots` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `boots` ;

-- -----------------------------------------------------
-- Table `boots`.`seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boots`.`seasons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `season` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `season` (`season` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `boots`.`boots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boots`.`boots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model_name` VARCHAR(30) NULL DEFAULT NULL,
  `price` DECIMAL(8,2) NULL DEFAULT NULL,
  `count` INT NULL DEFAULT NULL,
  `img` VARCHAR(50) NULL DEFAULT NULL,
  `id_season` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_season` (`id_season` ASC) VISIBLE,
  CONSTRAINT `boots_ibfk_1`
    FOREIGN KEY (`id_season`)
    REFERENCES `boots`.`seasons` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `boots`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boots`.`basket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_boots` INT NULL DEFAULT NULL,
  `count` INT NULL DEFAULT NULL,
  `datet_time` DATETIME NULL DEFAULT NULL,
  `customer` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_boots` (`id_boots` ASC) VISIBLE,
  CONSTRAINT `basket_ibfk_1`
    FOREIGN KEY (`id_boots`)
    REFERENCES `boots`.`boots` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `boots` ;

-- -----------------------------------------------------
-- procedure sp_item
-- -----------------------------------------------------

DELIMITER $$
USE `boots`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_item`()
BEGIN
    SELECT basket.customer, 
           basket.count, 
           basket.count * boots.price AS total_price, 
           seasons.season, 
           boots.model_name, 
           boots.count, 
           boots.price, 
           basket.datet_time,
           boots.img
    FROM basket 
    JOIN boots ON basket.id_boots = boots.id 
    JOIN seasons ON boots.id_season = seasons.id;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `boots`;

DELIMITER $$
USE `boots`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `boots`.`update_basket`
AFTER INSERT ON `boots`.`basket`
FOR EACH ROW
begin
declare c int;
select count into c from basket where id = new.id;
update boots
set count = count - c
where id = new.id_boots;
end$$


DELIMITER ;
